### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wakakkakak** [faresbougourzi/PAGTransYnet#1]
Hello, thank you for your contribution! I  would like to ask, in the process of running the code, it reported the following error, how should I fix it? I look forward to hearing from you!

urllib3.exceptions.SSLError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python\Anaconda\envs\building\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Python\Anaconda\envs\building\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "D:\Python\Anaconda\envs\building\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/pvt_v2_b2_li.in1k/resolve/main/model.safetensors (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\BuildFormer-main\train_supervision.py", line 234, in <module>
    main()
  File "D:\code\BuildFormer-main\train_supervision.py", line 213, in main
    config = py2cfg(args.config_path)
  File "D:\code\BuildFormer-main\tools\cfg.py", line 67, in py2cfg
    cfg_dict = py2dict(file_path)
  File "D:\code\BuildFormer-main\tools\cfg.py", line 59, in py2dict
    mod = import_module(module_name)
  File "D:\Python\Anaconda\envs\building\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\code\BuildFormer-main\config\whubuilding\buildformer_commen.py", line 4, in <module>
    from geoseg.models.PAG_TransYnet import PAGTransYnet
  File "D:\code\BuildFormer-main\geoseg\models\PAG_TransYnet.py", line 382, in <module>
    net = PAGTransYnet(input_channels=3, num_classes= 9)
  File "D:\code\BuildFormer-main\geoseg\models\PAG_TransYnet.py", line 275, in __init__
    self.transformer = timm.create_model(
  File "D:\Python\Anaconda\envs\building\lib\site-packages\timm\models\_factory.py", line 117, in create_model
    model = create_fn(
  File "D:\Python\Anaconda\envs\building\lib\site-packages\timm\models\pvt_v2.py", line 502, in pvt_v2_b2_li
    return _create_pvt2('pvt_v2_b2_li', pretrained=pretrained, **dict(model_args, **kwargs))
  File "D:\Python\Anaconda\envs\building\lib\site-packages\timm\models\pvt_v2.py", line 429, in _create_pvt2
    model = build_model_with_cfg(
  File "D:\Python\Anaconda\envs\building\lib\site-packages\timm\models\_builder.py", line 410, in build_model_with_cfg
    load_pretrained(
  File "D:\Python\Anaconda\envs\building\lib\site-packages\timm\models\_builder.py", line 190, in load_pretrained
    state_dict = load_state_dict_from_hf(pretrained_loc)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\timm\models\_hub.py", line 179, in load_state_dict_from_hf
    cached_safe_file = hf_hub_download(repo_id=hf_model_id, filename=safe_filename, revision=hf_revision)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\huggingface_hub\file_download.py", line 1261, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "D:\Python\Anaconda\envs\building\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\huggingface_hub\file_download.py", line 1667, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\Python\Anaconda\envs\building\lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
    response = _request_wrapper(
  File "D:\Python\Anaconda\envs\building\lib\site-packages\huggingface_hub\file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "D:\Python\Anaconda\envs\building\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/pvt_v2_b2_li.in1k/resolve/main/model.safetensors (Caused by ProxyError('Unable to connect to proxy', SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))))"), '(Request ID: c0e7cb20-0025-467e-938d-bd7e49cf6325)')

Process finished with exit code 1

**Comment by faresbougourzi** [comment]
Hi apparently, you have a problem in downloading PVT v2 pretrained weights from HaggingFace, you need to check your network connection or you can Download Manually:
If the issue persists, try downloading the file manually from the URL mentioned in the error (https://huggingface.co/timm/pvt_v2_b2_li.in1k/resolve/main/model.safetensors) and place it in the expected directory.
